// Encrypts data.js -> data.enc.js using AES-256-GCM with PBKDF2-derived key.
// Usage:  PASSWORD='your-password' node build.js

const fs = require("fs");
const crypto = require("crypto");
const path = require("path");

const password = process.env.PASSWORD;
if (!password) {
  console.error("Set PASSWORD env var. Example: PASSWORD='secret' node build.js");
  process.exit(1);
}
const dataPath = path.join(__dirname, "data.js");
const outPath = path.join(__dirname, "data.enc.js");

// Load the trip data via require (data.js exports it).
delete require.cache[dataPath];
const tripData = require(dataPath);

if (!tripData || !tripData.STOPS || !tripData.LOGISTICS) {
  console.error("data.js did not export {STOPS, LOGISTICS}.");
  process.exit(1);
}

const json = JSON.stringify(tripData);

const salt = crypto.randomBytes(16);
const iv = crypto.randomBytes(12);
const ITER = 200_000;
const key = crypto.pbkdf2Sync(password, salt, ITER, 32, "sha256");

const cipher = crypto.createCipheriv("aes-256-gcm", key, iv);
const ct = Buffer.concat([cipher.update(json, "utf8"), cipher.final()]);
const tag = cipher.getAuthTag();

// Layout: [16B salt][12B iv][16B tag][...ct]
const blob = Buffer.concat([salt, iv, tag, ct]).toString("base64");

const out = `// Auto-generated by build.js — do not edit by hand.
// AES-256-GCM, PBKDF2(SHA-256, ${ITER} iters). Layout: salt(16) | iv(12) | tag(16) | ct.
window.__ENCRYPTED_DATA = "${blob}";
window.__ENCRYPTED_META = { iter: ${ITER} };
`;

fs.writeFileSync(outPath, out);
console.log(`Wrote ${outPath} (${ct.length} bytes ciphertext, ${blob.length} chars base64)`);
